// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wilajhccewvbrsguyass.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpbGFqaGNjZXd2YnJzZ3V5YXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODc1MzIsImV4cCI6MjA2NjI2MzUzMn0.QcpHTjmEzdNCeYonpW_LmxDAjazndjwkkfe4k3m8C3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);